### ISSUE TITLE
Run sample.py failed:  OSError: libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zyx5256** [luost26/3D-Generative-SBDD#22]
--------------------------------------------- Error Information --------------------------------------

(SBDD-3D) root@10-90-43-152:/home/jenkins/zhuyuxiao/SBDD_Project/3D-Generative-SBDD# python sample.py ./configs/sample.yml --data_id {i}
Traceback (most recent call last):
  File "sample.py", line 7, in <module>
    from torch_geometric.data import Batch
  File "/home/miniconda3/envs/SBDD-3D/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/miniconda3/envs/SBDD-3D/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/miniconda3/envs/SBDD-3D/lib/python3.8/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/home/miniconda3/envs/SBDD-3D/lib/python3.8/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/home/miniconda3/envs/SBDD-3D/lib/python3.8/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/miniconda3/envs/SBDD-3D/lib/python3.8/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/miniconda3/envs/SBDD-3D/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory

--------------------------------------------- My Conda Env --------------------------------------

# packages in environment at /home/miniconda3/envs/SBDD-3D:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.0.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.7.4.post0      py38h497a2fe_0    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
biopython                 1.79             py38h497a2fe_0    conda-forge
blas                      1.0                         mkl    conda-forge
blinker                   1.4                        py_1    conda-forge
boost                     1.74.0           py38hc10631b_3    conda-forge
boost-cpp                 1.74.0               h9359b55_0    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f8727e_0    defaults
ca-certificates           2022.07.19           h06a4308_0    defaults
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    conda-forge
certifi                   2022.6.15        py38h578d9bd_0    conda-forge
cffi                      1.14.6           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_3    conda-forge
charset-normalizer        2.0.10             pyhd8ed1ab_0    conda-forge
click                     8.0.3            py38h578d9bd_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cpuonly                   2.0                           0    pytorch
cryptography              35.0.0           py38ha5dfef3_0    conda-forge
cudatoolkit               11.3.1               h2bc3f7f_2    defaults
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
decorator                 4.4.2                      py_0    conda-forge
easydict                  1.9                        py_0    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
fontconfig                2.13.1            hba837de_1005    conda-forge
freetype                  2.11.0               h70c0345_0    defaults
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.69.1               h4ff587b_1    defaults
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.15               he1e5248_0    defaults
google-auth               2.3.3              pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
grpcio                    1.42.0           py38hce63b2e_0    defaults
icu                       67.1                 he1b5a44_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
importlib-metadata        4.10.0           py38h578d9bd_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561    defaults
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.1            py38h1fd1430_1    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
libidn2                   2.3.2                h7f98852_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.15.8               h780b84a_0    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libtasn1                  4.16.0               h27cfd23_0    defaults
libtiff                   4.2.0                hbd63e13_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.40.0               h7f98852_0    conda-forge
libwebp                   1.2.0                h3452ae3_0    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.10               h72b56ed_2    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
matplotlib-base           3.3.4            py38h0efea84_0    conda-forge
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py38h497a2fe_0    conda-forge
mkl_fft                   1.3.1            py38hd3c417c_0    defaults
mkl_random                1.2.2            py38h1abd341_0    conda-forge
multidict                 5.2.0            py38h7f8727e_2    defaults
ncurses                   6.3                  h7f8727e_2    defaults
nettle                    3.7.3                hbbd107a_1    defaults
networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
numpy                     1.21.2           py38h20f2e39_0    defaults
numpy-base                1.21.2           py38h79a1101_0    defaults
oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openbabel                 3.1.1            py38hf4b5c11_1    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
pandas                    1.2.5            py38h1abd341_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    8.4.0            py38h5aabda8_0    defaults
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
protobuf                  3.15.8           py38h709712a_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycairo                   1.20.1           py38hf61ee4a_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyg                       2.0.3           py38_torch_1.10.0_cpu    pyg
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_5    conda-forge
python                    3.8.12               h12debd9_0    defaults
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-lmdb               0.99             py38h709712a_0    conda-forge
python-louvain            0.15               pyhd8ed1ab_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.10.1              py3.8_cpu_0    pytorch
pytorch-cluster           1.5.9           py38_torch_1.10.0_cu113    pyg
pytorch-mutex             1.0                         cpu    pytorch
pytorch-scatter           2.0.9           py38_torch_1.10.0_cu113    pyg
pytorch-sparse            0.6.12          py38_torch_1.10.0_cu113    pyg
pytorch-spline-conv       1.2.1           py38_torch_1.10.0_cu113    pyg
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
rdkit                     2020.09.5        py38h2bca085_0    conda-forge
readline                  8.1.2                h7f8727e_1    defaults
reportlab                 3.5.68           py38hadf75a6_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
scikit-learn              1.0.2            py38h51133e4_1    defaults
scipy                     1.7.3            py38hc147768_0    defaults
setuptools                58.0.4           py38h578d9bd_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlalchemy                1.3.23           py38h497a2fe_0    conda-forge
sqlite                    3.37.0               hc218d9a_0    defaults
tensorboard               2.7.0              pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.6.0            py38h2b97feb_0    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h21135ba_0    conda-forge
torchaudio                0.10.1               py38_cu113    pytorch
torchvision               0.11.2               py38_cu113    pytorch
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
typing-extensions         3.10.0.2             hd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.6.3            py38h497a2fe_2    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by luost26** [comment]
Hi,

Thank you for your interest in our work.

Can you try our latest work on SBDD? It is available at https://github.com/pengxingang/Pocket2Mol
It is based on the current work, but it is more efficient and stable.
